package entity

type RpgStats struct {
	Level     int     `json:"level"`
	Exp       int     `json:"exp"`
	Health    int     `json:"health"`
	Mana      int     `json:"mana"`
	Inventory MapData `json:"inventory"`
}

type JailStats struct {
	Status bool   `json:"status"`
	Reason string `json:"reason,omitempty"`
	Until  int64  `json:"until"`
}

type MapData map[string]interface{}

type User struct {
	// Identity
	UserID   string `json:"userId"` // key
	Username string `json:"username"`
	Name     string `json:"name"`
	Age      int    `json:"age"`

	// Core Stats
	Money      float64 `json:"money"`
	Bank       float64 `json:"bank"`
	Diamond    float64 `json:"diamond"`
	Registered bool    `json:"registered"`
	RegTime    int64   `json:"regTime"`

	// Nested Objects
	Rpg       RpgStats  `json:"rpg"`
	Jail      JailStats `json:"jail"`
	Items     MapData   `json:"items"`
	LastTimes MapData   `json:"last_times"`
}

// mapping data user
func GetDefaultUserMap() map[string]interface{} {
	return map[string]interface{}{
		"username":   "",
		"name":       "",
		"age":        -1,
		"registered": false,
		"regTime":    -1,
		"money":      100000.0,
		"role":       "Newbie ㋡",
		"location":   "Gubuk",

		// --- Cooldowns & Activity ---
		"lastDaily":     0.0,
		"lastWeekly":    0.0,
		"limit":         10.0,
		"pasangan":      "",
		"proposalFrom":  nil,
		"sahabat":       "",
		"lastjobkerja":  0.0,
		"lastjobchange": 0.0,

		// --- Nested Objects (PENTING) ---
		"rpg": map[string]interface{}{
			"level":     1.0,
			"exp":       0.0,
			"health":    100.0,
			"mana":      50.0,
			"inventory": map[string]interface{}{}, // Object kosong
		},

		"jail": map[string]interface{}{
			"status": false,
			"reason": nil,
			"until":  0.0,
		},

		"motor": map[string]interface{}{
			"Name":          "",
			"Bensin":        0.0,
			"Durability":    0.0,
			"MaxDurability": 100.0,
			"maxBensin":     100.0,
		},
		"motorGrade2": map[string]interface{}{
			"Name":          "",
			"Bensin":        0.0,
			"Durability":    0.0,
			"maxBensin":     200.0,
			"MaxDurability": 250.0,
		},
		"motorGrade3": map[string]interface{}{
			"Name":          "",
			"Bensin":        0.0,
			"Durability":    0.0,
			"maxBensin":     300.0,
			"MaxDurability": 350.0,
		},
		// --- Transport & Jobs ---
		"taxi":          0.0,
		"lasttaxi":      0.0,
		"lastyoutuber":  0.0,
		"subscribers":   0.0,
		"viewers":       0.0,
		"like":          0.0,
		"playButton":    0.0,
		"saldo":         0.0,
		"pengeluaran":   0.0,
		"energi":        100.0,
		"power":         100.0,
		"title":         "",
		"haus":          100.0,
		"laper":         100.0,
		"tprem":         0.0,
		"stamina":       100.0,
		"Health":        100.0,
		"follow":        0.0,
		"lastfollow":    0.0,
		"followers":     0.0,
		"titlein":       "Belum Ada",
		"ultah":         "",
		"pc":            0.0,
		"coin":          0.0,
		"atm":           0.0,
		"skata":         0.0,
		"tigame":        999.0,
		"lastclaim":     0.0,
		"judilast":      0.0,
		"lastnambang":   0.0,
		"lastnebang":    0.0,
		"lastmulung":    0.0,
		"lastkerja":     0.0,
		"lastmaling":    0.0,
		"lastbunuhi":    0.0,
		"lastbisnis":    0.0,
		"lastberbisnis": 0.0,
		"bisnis":        0.0,
		"berbisnis":     0.0,
		"lastmancing":   0.0,

		// --- Items & Inventory ---
		"pancing":        0.0,
		"pancingan":      0.0,
		"totalPancingan": 0.0,
		"kardus":         0.0,
		"botol":          0.0,
		"kaleng":         0.0,
		"litecoin":       0.0,
		"chip":           0.0,
		"tiketcoin":      0.0,
		"poin":           0.0,
		"bank":           0.0,
		"balance":        0.0,
		"diamond":        0.0,
		"emerald":        0.0,
		"rock":           0.0,
		"wood":           0.0,
		"berlian":        0.0,
		"iron":           0.0,
		"emas":           0.0,
		"common":         0.0,
		"uncommon":       0.0,
		"mythic":         0.0,
		"legendary":      0.0,
		"rumahsakit":     0.0,
		"tambang":        0.0,
		"camptroops":     0.0,
		"pertanian":      0.0,
		"fortress":       0.0,
		"trofi":          0.0,
		"rtrofi":         "perunggu",
		"makanan":        0.0,
		"troopcamp":      0.0,
		"shield":         0.0,
		"arlok":          0.0,
		"ojekk":          0.0,
		"ojek":           0.0,
		"lastngewe":      0.0,
		"ngewe":          0.0,
		"polisi":         0.0,
		"pedagang":       0.0,
		"dokter":         0.0,
		"petani":         0.0,
		"montir":         0.0,
		"kuli":           0.0,
		"korbanngocok":   0.0,
		"coal":           0.0,
		"korekapi":       0.0,

		// --- Foods ---
		"ayambakar":       0.0,
		"gulai":           0.0,
		"rendang":         0.0,
		"ayamgoreng":      0.0,
		"oporayam":        0.0,
		"steak":           0.0,
		"babipanggang":    0.0,
		"ikanbakar":       0.0,
		"lelebakar":       0.0,
		"nilabakar":       0.0,
		"bawalbakar":      0.0,
		"udangbakar":      0.0,
		"pausbakar":       0.0,
		"kepitingbakar":   0.0,
		"soda":            0.0,
		"vodka":           0.0,
		"ganja":           0.0,
		"bandage":         0.0,
		"sushi":           0.0,
		"roti":            0.0,
		"ramuan":          0.0,
		"lastramuanclaim": 0.0,
		"gems":            0.0,
		"cupon":           0.0,
		"lastgemsclaim":   0.0,
		"eleksirb":        0.0,
		"penduduk":        0.0,
		"archer":          0.0,
		"shadow":          0.0,

		// --- Claims ---
		"laststringclaim":  0.0,
		"lastpotionclaim":  0.0,
		"lastswordclaim":   0.0,
		"lastweaponclaim":  0.0,
		"lastironclaim":    0.0,
		"lastslot":         0.0,
		"lastmancingclaim": 0.0,

		// --- Fishing Catches ---
		"anakpancingan": 0.0,
		"as":            0.0,
		"paus":          0.0,
		"kepiting":      0.0,
		"gurita":        0.0,
		"cumi":          0.0,
		"buntal":        0.0,
		"dory":          0.0,
		"lumba":         0.0,
		"lobster":       0.0,
		"hiu":           0.0,
		"lele":          0.0,
		"nila":          0.0,
		"bawal":         0.0,
		"udang":         0.0,
		"ikan":          0.0,
		"orca":          0.0,

		// --- Animals ---
		"banteng":   0.0,
		"harimau":   0.0,
		"gajah":     0.0,
		"kambing":   0.0,
		"panda":     0.0,
		"buaya":     0.0,
		"kerbau":    0.0,
		"sapi":      0.0,
		"monyet":    0.0,
		"babihutan": 0.0,
		"babi":      0.0,
		"ayam":      0.0,
		"ayamb":     0.0,
		"ayamg":     0.0,
		"ssapi":     0.0,
		"sapir":     0.0,
		"leleb":     0.0,
		"leleg":     0.0,
		"esteh":     0.0,
		"pet":       0.0,
		"potion":    0.0,
		"sampah":    0.0,

		// --- Mythical Pets ---
		"kucing":            0.0,
		"kucinglastclaim":   0.0,
		"kucingexp":         0.0,
		"kuda":              0.0,
		"kudalastclaim":     0.0,
		"rubah":             0.0,
		"rubahlastclaim":    0.0,
		"rubahexp":          0.0,
		"anjing":            0.0,
		"anjinglastclaim":   0.0,
		"anjingexp":         0.0,
		"naga":              0.0,
		"nagalastclaim":     0.0,
		"griffin":           0.0,
		"griffinlastclaim":  0.0,
		"centaur":           0.0,
		"fightnaga":         0.0,
		"centaurlastclaim":  0.0,
		"serigala":          0.0,
		"serigalalastclaim": 0.0,
		"serigalaexp":       0.0,
		"phonix":            0.0,
		"phonixlastclaim":   0.0,
		"phonixexp":         0.0,

		// --- Pet Food ---
		"makanannaga":     0.0,
		"makananphonix":   0.0,
		"makanancentaur":  0.0,
		"makananserigala": 0.0,
		"makananpet":      0.0,
		"anakkucing":      0.0,
		"anakkuda":        0.0,
		"anakrubah":       0.0,
		"anakanjing":      0.0,
		"anakserigala":    0.0,
		"anaknaga":        0.0,
		"anakphonix":      0.0,
		"anakgriffin":     0.0,
		"anakkyubi":       0.0,
		"anakcentaur":     0.0,

		// --- System ---
		"BannedReason":      "",
		"bannedTime":        0.0,
		"banned":            false,
		"warn":              0.0,
		"afk":               -1.0,
		"afkReason":         "",
		"antispam":          0.0,
		"antispamlastclaim": 0.0,

		// --- Materials & Tools ---
		"kayu":                 0.0,
		"batu":                 0.0,
		"string":               0.0,
		"umpan":                0.0,
		"armor":                0.0,
		"armordurability":      0.0,
		"weapon":               0.0,
		"weapondurability":     0.0,
		"sword":                0.0,
		"sworddurability":      0.0,
		"pickaxe":              0.0,
		"pickaxedurability":    0.0,
		"fishingrod":           0.0,
		"fishingroddurability": 0.0,
		"katana":               0.0,
		"katanadurability":     0.0,
		"bow":                  0.0,
		"bowdurability":        0.0,
		"kapak":                0.0,
		"kapakdurability":      0.0,
		"axe":                  0.0,
		"axedurability":        0.0,
		"pisau":                0.0,
		"pisaudurability":      0.0,

		// --- Jobs Counters ---
		"kerjasatu":           0.0,
		"kerjadua":            0.0,
		"kerjatiga":           0.0,
		"kerjaempat":          0.0,
		"kerjalima":           0.0,
		"kerjaenam":           0.0,
		"kerjatujuh":          0.0,
		"kerjadelapan":        0.0,
		"kerjasembilan":       0.0,
		"kerjasepuluh":        0.0,
		"kerjasebelas":        0.0,
		"kerjaduabelas":       0.0,
		"kerjatigabelas":      0.0,
		"kerjaempatbelas":     0.0,
		"kerjalimabelas":      0.0,
		"pekerjaansatu":       0.0,
		"pekerjaandua":        0.0,
		"pekerjaantiga":       0.0,
		"pekerjaanempat":      0.0,
		"pekerjaanlima":       0.0,
		"pekerjaanenam":       0.0,
		"pekerjaantujuh":      0.0,
		"pekerjaandelapan":    0.0,
		"pekerjaansembilan":   0.0,
		"pekerjaansepuluh":    0.0,
		"pekerjaansebelas":    0.0,
		"pekerjaanduabelas":   0.0,
		"pekerjaantigabelas":  0.0,
		"pekerjaanempatbelas": 0.0,
		"pekerjaanlimabelas":  0.0,

		// --- Last Times ---
		"lastadventure": 0.0,
		"lastwar":       0.0,
		"lastberkebon":  0.0,
		"lastberburu":   0.0,
		"lastbansos":    0.0,
		"lastrampok":    0.0,
		"lastkill":      0.0,
		"lastfishing":   0.0,
		"lastdungeon":   0.0,
		"lastduel":      0.0,
		"lastmining":    0.0,
		"lasthourly":    0.0,
		"lastdagang":    0.0,
		"lasthunt":      0.0,
		"lasthun":       0.0,
		"lastmonthly":   0.0,
		"lastyearly":    0.0,
		"lastjb":        0.0,
		"lastrob":       0.0,
		"lastdaang":     0.0,
		"lastngojek":    0.0,
		"lastgrab":      0.0,
		"lastngocok":    0.0,
		"lastturu":      0.0,
		"lastseen":      0.0,
		"lastSetStatus": 0.0,

		// --- Status ---
		"premiumDate": -1.0,
		"premiumTime": 0.0,
		"vip":         "tidak",
		"vipPoin":     0.0,
		"job":         "Pengangguran",
		"jobexp":      0.0,
		"penjara":     false,
		"antarpaket":  0.0,
		"dirawat":     false,
		"lbars":       "[▒▒▒▒▒▒▒▒▒]",
		"skill":       "",
		"korps":       "",
		"korpsgrade":  "",

		// --- Demon Slayer Stats ---
		"demon":          "",
		"breaths":        "",
		"magic":          "",
		"darahiblis":     0.0,
		"demonblood":     0.0,
		"demonkill":      0.0,
		"hashirakill":    0.0,
		"alldemonkill":   0.0,
		"allhashirakill": 0.0,
		"attack":         0.0,
		"speed":          0.0,
		"strenght":       0.0,
		"defense":        0.0,
		"regeneration":   0.0,

		// --- E-Wallet & Farming ---
		"ovo":           0.0,
		"dana":          0.0,
		"gopay":         0.0,
		"lastngaji":     0.0,
		"lastlonte":     0.0,
		"lastkoboy":     0.0,
		"lastdate":      0.0,
		"lasttambang":   0.0,
		"lastngepet":    0.0,
		"mangga":        0.0,
		"stroberi":      0.0,
		"semangka":      0.0,
		"jeruk":         0.0,
		"pisang":        0.0,
		"bibitanggur":   0.0,
		"bibitpisang":   0.0,
		"bibitapel":     0.0,
		"bibitmangga":   0.0,
		"bibitjeruk":    0.0,
		"healthmonster": 0.0,
		"kingdom":       false,
		"lastsda":       0.0,
		"lastberbru":    0.0,
		"lastgift":      0.0,
		"lastcodereg":   0.0,
		"jualan":        0.0,
		"lastjualan":    0.0,
		"ngocokk":       0.0,
		"lastngocokk":   0.0,
		"anggur":        0.0,
	}
}

func GetDefaultRPG() RpgStats {
	return RpgStats{
		Level: 1, Exp: 0, Health: 100, Mana: 50, Inventory: make(MapData),
	}
}
